-- AlterTable
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "traits" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "hairColor" TEXT NOT NULL DEFAULT '#1a1a1a';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "skinColor" TEXT NOT NULL DEFAULT '#e899a3';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "shirtColor" TEXT NOT NULL DEFAULT '#0f1e3d';
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "pantsColor" TEXT NOT NULL DEFAULT '#4b250a';
